#!/bin/sh

unset INT_ARRAY
unset STRING_ARRAY
unset TUPLE_ARRAY
unset EXPLICIT_OVERRIDE_ISIZE
unset EXPLICIT_OVERRIDE_F64
unset IMPLICIT_ISIZE
unset IMPLICIT_F64
unset NEGATIVE_I16
unset NEGATIVE_ISIZE
unset NEGATIVE_F32
unset QUOTED_STR
unset QUOTED_BYTE_STR
unset SMOKE_STR
unset SMOKE_U32
unset ORIGIN