name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run nighly tracking tests
      run: cd const_env_tests && source set-env.sh && cargo +nightly run
    - name: Run non-nightly tracking tests
      run: cd const_env_tests && ./run-tracking-tests.sh

